# Generated by Django 4.2.5 on 2023-10-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinova_app', '0003_favoritemovie_description_favoritemovie_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemovie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='favoritemovie',
            name='link',
        ),
        migrations.RemoveField(
            model_name='favoritemovie',
            name='name',
        ),
        migrations.RemoveField(
            model_name='favoritemovie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='favoritemovie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='favoritemovie',
            name='year',
        ),
    ]
