# Generated by Django 4.2.5 on 2023-10-29 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinova_app', '0004_remove_favoritemovie_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('positive', 'Положительный'), ('negative', 'Отрицательный'), ('neutral', 'Нейтральный')], max_length=10)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
