# Generated by Django 4.2.5 on 2023-11-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinova_app', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.IntegerField(null=True),
        ),
    ]
